# Generated by Django 5.2.1 on 2025-08-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidaterevenue_candidaterevenuefeedback'),
        ('jobopening', '0002_jobopening_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjob',
            name='job_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_applications', to='jobopening.jobopening'),
        ),
    ]
