# Generated by Django 5.2.1 on 2025-08-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_clientjob_job_opening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientjob',
            name='job_opening',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
