# Generated by Django 5.2.1 on 2025-08-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_remove_clientjob_job_opening_alter_candidate_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatefeedback',
            name='feedback_file',
        ),
        migrations.AddField(
            model_name='candidatefeedback',
            name='client_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='candidate.clientjob'),
        ),
        migrations.AlterField(
            model_name='candidatefeedback',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
