# Generated by Django 5.2.1 on 2025-09-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidate_feedback_date_candidate_feedback_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='feedback_text',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='feedback_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='feedback_status',
        ),
    ]
