# Generated by Django 5.2.1 on 2025-09-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_rename_feedback_text_candidate_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientjob',
            name='expected_joining_date',
        ),
        migrations.RemoveField(
            model_name='clientjob',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='clientjob',
            name='next_follow_up_date',
        ),
        migrations.RemoveField(
            model_name='clientjob',
            name='remarks',
        ),
    ]
