# Generated by Django 5.2.1 on 2025-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_remove_clientjob_expected_joining_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='feedback',
        ),
        migrations.AddField(
            model_name='clientjob',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
