# Generated by Django 5.2.1 on 2025-09-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_remove_clientjob_job_opening_alter_candidate_gender'),
        ('candidate', '0012_clientjob_expected_joining_date_and_more'),
    ]

    operations = [
    ]
