# Generated by Django 5.2.1 on 2025-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_remove_candidate_compressed_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
