# Generated by Django 5.2.1 on 2025-09-16 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_candidate_resume_parsed_data_candidate_resume_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_additionalinfo', to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='educationcertificate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_educationcertificate', to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='experiencecompany',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_experiencecompany', to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='previouscompany',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_previouscompany', to='candidate.candidate'),
        ),
    ]
