# Generated by Django 5.2.1 on 2025-09-25 07:17

from django.db import migrations, models


def no_op(apps, schema_editor):
    """
    No-op function since the assign_by and assign_to fields already exist in the database.
    This migration was created to add fields that already exist.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_alter_additionalinfo_candidate_and_more'),
    ]

    operations = [
        # No-op migration since the assign_by and assign_to fields already exist in the database
        migrations.RunPython(no_op, no_op),
    ]
