# Generated by Django 4.2.7 on 2025-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_clientjob_assign_clientjob_assign_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientjob',
            options={'ordering': ['-transfer_date', '-updated_at']},
        ),
        migrations.AddField(
            model_name='clientjob',
            name='assigned_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['assign_to', 'assign', 'transfer_date'], name='idx_assign_to_status_date'),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['assigned_from', 'assign', 'transfer_date'], name='idx_assigned_from_status_date'),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['transfer_date'], name='idx_transfer_date'),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['assign', 'assign_to'], name='idx_assign_status_to'),
        ),
    ]
