# Generated by Django 4.2.7 on 2025-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0026_skip_added_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenuefeedback',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientjob',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationcertificate',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencecompany',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobassignmenthistory',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='previouscompany',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
