# Generated by Django 4.2.7 on 2025-11-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0027_alter_additionalinfo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-updated_at'], name='candidate_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['executive_name'], name='candidate_executive_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['city'], name='candidate_city_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['state'], name='candidate_state_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['created_by'], name='candidate_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['candidate', 'remarks'], name='clientjob_cand_remark_idx'),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['remarks'], name='clientjob_remarks_idx'),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['client_name'], name='clientjob_client_idx'),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['-updated_at'], name='clientjob_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['candidate', '-updated_at'], name='clientjob_cand_updated_idx'),
        ),
    ]
