# Generated by Django 4.2.7 on 2025-11-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0032_add_client_fields_to_status_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatushistory',
            name='profile_submission',
            field=models.BooleanField(default=False, help_text='Profile submission status'),
        ),
    ]
