# Generated by Django 4.2.7 on 2025-11-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0033_candidatestatushistory_profile_submission'),
        ('candidate', '0034_change_profile_submission_to_integer'),
    ]

    operations = [
    ]
