# Generated by Django 4.2.7 on 2025-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0035_merge_20251121_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatushistory',
            name='profile_submission',
            field=models.IntegerField(blank=True, help_text='Profile submission status (1=Yes, 0=No)', null=True),
        ),
    ]
