# Generated by Django 5.2.1 on 2025-10-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_call_plan_id', models.IntegerField(blank=True, null=True)),
                ('tb_call_plan_data', models.CharField(default='P1', max_length=20)),
                ('tb_call_emp_id', models.IntegerField(default=1)),
                ('tb_call_client_id', models.IntegerField(default=1)),
                ('tb_call_state_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tb_call_city_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tb_call_channel', models.CharField(default='General Position', max_length=200)),
                ('tb_call_channel_id', models.IntegerField(blank=True, null=True)),
                ('tb_call_source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tb_call_description', models.TextField(default='Event description')),
                ('tb_call_startdate', models.DateTimeField()),
                ('tb_call_todate', models.DateTimeField()),
                ('tb_calls_onplan', models.TextField(blank=True, null=True)),
                ('tb_calls_onothers', models.TextField(blank=True, null=True)),
                ('tb_calls_profiles', models.TextField(blank=True, null=True)),
                ('tb_calls_profilesothers', models.TextField(blank=True, null=True)),
                ('tb_call_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Completed'), (3, 'Cancelled')], default=1)),
                ('tb_call_add_date', models.DateTimeField(auto_now_add=True)),
                ('tb_call_up_date', models.DateTimeField(auto_now=True)),
                ('employee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('source_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Call Detail',
                'verbose_name_plural': 'Call Details',
                'db_table': 'tb_call_details',
                'ordering': ['-tb_call_add_date'],
            },
        ),
    ]
