# Generated by Django 5.2.1 on 2025-08-30 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('ctc', models.IntegerField(blank=True, null=True)),
                ('additionalDocuments', models.FileField(blank=True, null=True, upload_to='additional_documents/')),
                ('bloodGroup', models.CharField(max_length=3)),
                ('dateOfBirth', models.DateField()),
                ('employeeID', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('del_state', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(default='Default', max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('last_name', models.CharField(default='Default', max_length=100)),
                ('marital_status', models.CharField(default='Single', max_length=20)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='proof_documents/')),
                ('proof_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('work_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('confirmPassword', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
