# Generated by Django 5.2.1 on 2025-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experienceDetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
