# Generated by Django 5.2.1 on 2025-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0002_employee_experiencedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lastCompany',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
