# Generated by Django 5.2.1 on 2025-08-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0003_employee_lastcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currentAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergencyContact1Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergencyContact1Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergencyContact2Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergencyContact2Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
