# Generated by Django 5.2.1 on 2025-09-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0004_employee_currentaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='joining_date',
            new_name='joiningDate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='marital_status',
            new_name='maritalStatus',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='official_email',
            new_name='officialEmail',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='permanent_address',
            new_name='permanentAddress',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='personal_email',
            new_name='personalEmail',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='profile_photo',
            new_name='profilePhoto',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='proof_document',
            new_name='proofDocument',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='proof_type',
            new_name='proofType',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='reference_contact_name',
            new_name='referenceContactName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='reference_contact_phone',
            new_name='referenceContactPhone',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='reporting_manager',
            new_name='reportingManager',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='work_mode',
            new_name='workMode',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='years_of_experience',
            new_name='yearsOfExperience',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeeID',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeCode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
