# Generated by Django 5.2.1 on 2025-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0006_alter_employee_bloodgroup_alter_employee_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emergencyContact2Name',
            new_name='accountHolderName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='confirmPassword',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergencyContact2Phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhaarBack',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhaarFront',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhaarNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bankName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifscCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='offerLetterFiles',
            field=models.FileField(blank=True, null=True, upload_to='documents/offer_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='panFiles',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='panNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='payslipFiles',
            field=models.FileField(blank=True, null=True, upload_to='documents/payslips/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='relievingLetterFiles',
            field=models.FileField(blank=True, null=True, upload_to='documents/relieving_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='upiNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
