# Generated by Django 5.2.1 on 2025-09-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0007_rename_emergencycontact2name_employee_accountholdername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='additionalDocuments',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='proofDocument',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='proofType',
        ),
    ]
