# Generated by Django 5.2.1 on 2025-09-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0008_remove_employee_additionaldocuments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='payslipFiles',
        ),
    ]
