# Generated by Django 5.2.1 on 2025-09-29 07:12

from django.db import migrations, models


def no_op(apps, schema_editor):
    """
    No-op function since the reportingManager field already exists in the database
    as 'reporting_manager'. The field structure is already correct.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0009_remove_employee_payslipfiles'),
    ]

    operations = [
        # No-op migration since the reportingManager field already exists
        migrations.RunPython(no_op, no_op),
    ]
