# Generated by Django 5.2.1 on 2025-09-29 07:27

from django.db import migrations, models


def no_op(apps, schema_editor):
    """
    No-op function since the reportingManager field already exists with correct structure.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0010_alter_employee_reportingmanager'),
    ]

    operations = [
        # No-op migration since the reportingManager field already exists with correct structure
        migrations.RunPython(no_op, no_op),
    ]
