# Generated by Django 5.2.1 on 2025-09-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0011_alter_employee_reportingmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reportingManager',
            field=models.CharField(blank=True, db_column='reportingManager_id', max_length=100, null=True),
        ),
    ]
