# Generated by Django 5.2.1 on 2025-10-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0012_alter_employee_reportingmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='paySlipFiles',
            field=models.FileField(blank=True, null=True, upload_to='documents/pay_slips/'),
        ),
    ]
