# Generated by Django 5.2.1 on 2025-10-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0013_employee_payslipfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='paySlipFiles',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='payslipFiles',
            field=models.FileField(blank=True, null=True, upload_to='documents/payslips/'),
        ),
    ]
