# Generated by Django 5.2.1 on 2025-08-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('executive_name', models.CharField(max_length=100)),
                ('candidate_name', models.CharField(max_length=100)),
                ('mobile1', models.CharField(max_length=15)),
                ('mobile2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('communication', models.CharField(blank=True, max_length=50, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_parsed_data', models.JSONField(blank=True, null=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='resumes/converted/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_two_wheeler', models.BooleanField(blank=True, default=None, null=True)),
                ('two_wheeler_license', models.BooleanField(blank=True, default=None, null=True)),
                ('license_expected_date', models.CharField(blank=True, max_length=100, null=True)),
                ('has_laptop', models.BooleanField(blank=True, default=None, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_text', models.TextField()),
                ('feedback_file', models.FileField(blank=True, null=True, upload_to='candidate_feedback/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('industry', models.JSONField(blank=True, null=True)),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('expected_joining_date', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('profile_submission', models.BooleanField(default=False)),
                ('profile_submission_date', models.DateField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_jobs', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50)),
                ('has_certificate', models.BooleanField(blank=True, default=None, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_certificates', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_letter', models.BooleanField(blank=True, default=None, null=True)),
                ('offer_letter_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('payslip', models.BooleanField(blank=True, default=None, null=True)),
                ('payslip_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('relieving_letter', models.BooleanField(blank=True, default=None, null=True)),
                ('relieving_letter_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=50, null=True)),
                ('incentives', models.BooleanField(blank=True, default=None, null=True)),
                ('incentive_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incentive_proof', models.BooleanField(blank=True, default=None, null=True)),
                ('incentive_proof_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('more_than_15_months', models.BooleanField(blank=True, default=None, null=True)),
                ('first_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_companies', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
