# Generated by Django 5.2.1 on 2025-08-19 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_letter', models.BooleanField(blank=True, default=None, null=True)),
                ('offer_letter_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('payslip', models.BooleanField(blank=True, default=None, null=True)),
                ('payslip_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('relieving_letter', models.BooleanField(blank=True, default=None, null=True)),
                ('relieving_letter_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_companies', to='candidate.candidate')),
                ('experience_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_companies', to='candidate.experiencecompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
