# Generated by Django 5.2.1 on 2025-08-25 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_previouscompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joining_date', models.DateField(blank=True, default=None, null=True)),
                ('accountable_ctc', models.IntegerField(blank=True, default=None, null=True)),
                ('offer_ctc', models.IntegerField(blank=True, default=None, null=True)),
                ('percentage', models.IntegerField(blank=True, default=None, null=True)),
                ('amount', models.IntegerField(blank=True, default=None, null=True)),
                ('revenue', models.IntegerField(blank=True, default=None, null=True)),
                ('revenue_status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('itbr_date', models.DateField(blank=True, default=None, null=True)),
                ('erd_date', models.DateField(blank=True, default=None, null=True)),
                ('br_date', models.DateField(blank=True, default=None, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('invoice_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateRevenueFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField()),
                ('candidate_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='candidate.candidaterevenue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
