# Generated by Django 5.2.1 on 2025-09-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_remove_candidatefeedback_feedback_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='feedback_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='feedback_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CandidateFeedback',
        ),
    ]
