# Generated by Django 5.2.1 on 2025-09-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_remove_candidate_feedback_clientjob_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjob',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
