# Generated by Django 5.2.1 on 2025-09-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_clientjob_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjob',
            name='expected_joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
