# Generated by Django 5.2.1 on 2025-09-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_candidate_compressed_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='compressed_file_size',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='original_file_size',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='original_file_type',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='processing_completed_at',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='processing_error',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='processing_started_at',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_compressed',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_parsed_data',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_text',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='upload_timestamp',
        ),
    ]
