# Generated by Django 5.2.1 on 2025-09-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_alter_additionalinfo_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='educationcertificate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_certificates', to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='experiencecompany',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_companies', to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='previouscompany',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_companies', to='candidate.candidate'),
        ),
    ]
