# Generated by Django 5.2.1 on 2025-09-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_unified_workflow'),
        ('candidate', '0019_clientjob_assign_by_clientjob_assign_to'),
    ]

    operations = [
    ]
