# Generated by Django 5.2.1 on 2025-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_merge_20250926_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='created_by',
            field=models.CharField(blank=True, help_text='Employee code of candidate creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Employee code of last updater', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_by',
            field=models.CharField(blank=True, help_text='Employee code of candidate creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='executive_name',
            field=models.CharField(help_text='Employee name who created this candidate', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Employee code of last updater', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='created_by',
            field=models.CharField(blank=True, help_text='Employee code of candidate creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Employee code of last updater', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenuefeedback',
            name='created_by',
            field=models.CharField(blank=True, help_text='Employee code of candidate creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenuefeedback',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Employee code of last updater', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientjob',
            name='created_by',
            field=models.CharField(blank=True, help_text='Employee code of candidate creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientjob',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Employee code of last updater', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationcertificate',
            name='created_by',
            field=models.CharField(blank=True, help_text='Employee code of candidate creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationcertificate',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Employee code of last updater', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencecompany',
            name='created_by',
            field=models.CharField(blank=True, help_text='Employee code of candidate creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencecompany',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Employee code of last updater', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobassignmenthistory',
            name='created_by',
            field=models.CharField(blank=True, help_text='Employee code of candidate creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobassignmenthistory',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Employee code of last updater', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='previouscompany',
            name='created_by',
            field=models.CharField(blank=True, help_text='Employee code of candidate creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='previouscompany',
            name='updated_by',
            field=models.CharField(blank=True, help_text='Employee code of last updater', max_length=100, null=True),
        ),
    ]
