# Generated by Django 5.2.1 on 2025-09-26 14:12

from django.db import migrations, models


def no_op(apps, schema_editor):
    """
    No-op function since the assign field already exists in the database.
    This migration was created to add a field that already exists.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_alter_additionalinfo_created_by_and_more'),
    ]

    operations = [
        # No-op migration since the assign field already exists in the database
        migrations.RunPython(no_op, no_op),
    ]
