# Generated by Django 5.2.1 on 2025-09-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_clientjob_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjob',
            name='assign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='assign_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='assign_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
