# Generated by Django 4.2.7 on 2025-10-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_alter_clientjob_options_clientjob_assigned_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientjob',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='clientjob',
            name='idx_assign_to_status_date',
        ),
        migrations.RemoveIndex(
            model_name='clientjob',
            name='idx_assigned_from_status_date',
        ),
        migrations.RemoveIndex(
            model_name='clientjob',
            name='idx_transfer_date',
        ),
        migrations.RemoveIndex(
            model_name='clientjob',
            name='idx_assign_status_to',
        ),
    ]
