# Generated by Django 4.2.7 on 2025-10-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0025_alter_clientjob_options_and_more'),
    ]

    operations = [
    ]
