# Generated by Django 4.2 on 2025-11-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_candidate_status_history'),
        ('candidate', '0029_alter_clientjob_options_clientjob_profilestatus_and_more'),
    ]

    operations = [
    ]
