# Generated by Django 4.2 on 2025-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0030_merge_20251114_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatushistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
