# Generated by Django 4.2 on 2025-11-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0033_add_profile_submission_to_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientjob',
            name='profile_submission',
            field=models.IntegerField(default=0),
        ),
    ]
