# Generated by Django 4.2.7 on 2025-11-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0036_fix_profile_submission_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatushistory',
            name='attend_flag',
            field=models.BooleanField(default=False, help_text='Attendance flag for the status change'),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='attend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='attend_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
