# Generated by Django 4.2.7 on 2025-12-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0037_candidatestatushistory_attend_flag_clientjob_attend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterevenue',
            name='accountable_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='offer_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
