# Generated by Django 4.2.7 on 2025-12-03 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0039_alter_candidaterevenue_accountable_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterevenue',
            name='client_job',
            field=models.ForeignKey(blank=True, help_text='The client job this revenue record is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='candidate.clientjob'),
        ),
        migrations.AddField(
            model_name='candidaterevenuefeedback',
            name='client_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='candidate.clientjob'),
        ),
    ]
