# Generated by Django 4.2.7 on 2025-12-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0040_candidaterevenue_client_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidaterevenuefeedback',
            name='client_job',
        ),
    ]
