# Generated by Django 4.2.7 on 2025-12-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0041_remove_candidaterevenuefeedback_client_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterevenue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
