# Generated by Django 4.2.7 on 2025-12-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0042_candidaterevenue_is_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidaterevenue',
            index=models.Index(fields=['created_at'], name='candidate_c_created_4acd1e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterevenue',
            index=models.Index(fields=['updated_at'], name='candidate_c_updated_af07a8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterevenue',
            index=models.Index(fields=['candidate'], name='candidate_c_candida_cefbf3_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaterevenue',
            index=models.Index(fields=['client_job'], name='candidate_c_client__667ef8_idx'),
        ),
    ]
