# Generated by Django 4.2.7 on 2025-12-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0043_candidaterevenue_candidate_c_created_4acd1e_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidaterevenue',
            index=models.Index(fields=['joining_date'], name='candidate_c_joining_b7bfd6_idx'),
        ),
    ]
