# Generated by Django 4.2.7 on 2025-12-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0044_candidaterevenue_candidate_c_joining_b7bfd6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterevenue',
            name='accountable_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='offer_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
