# Generated by Django 4.2.7 on 2025-12-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0045_alter_candidaterevenue_accountable_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterevenue',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
