# Generated by Django 4.2.7 on 2025-12-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0046_alter_candidaterevenue_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterevenue',
            name='accountable_ctc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='offer_ctc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='revenue',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
