# Generated by Django 4.2.7 on 2025-12-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0047_alter_candidaterevenue_accountable_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterevenue',
            name='accountable_ctc',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='amount',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='offer_ctc',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='percentage',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidaterevenue',
            name='revenue',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
