# Generated by Django 4.2.7 on 2025-12-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0048_alter_candidaterevenue_accountable_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterevenue',
            name='change_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
