# Generated by Django 4.2.7 on 2025-12-10 11:15
from django.db import migrations, models


def add_feedback_and_transfer_history_fields(apps, schema_editor):
    def column_exists(table_name, column_name):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            return cursor.fetchone()[0] > 0

    def safe_exec(sql):
        with schema_editor.connection.cursor() as cursor:
            try:
                cursor.execute(sql)
            except Exception:
                pass

    candidate_table = 'candidate_candidate'

    if not column_exists(candidate_table, 'feedback'):
        safe_exec("ALTER TABLE `candidate_candidate` ADD COLUMN `feedback` longtext NULL AFTER `resume_pdf`")

    if not column_exists(candidate_table, 'transfer_history'):
        safe_exec("ALTER TABLE `candidate_candidate` ADD COLUMN `transfer_history` longtext NULL AFTER `feedback`")


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0049_candidaterevenue_change_history'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_feedback_and_transfer_history_fields, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='candidate',
                    name='feedback',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='candidate',
                    name='transfer_history',
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
    ]
