# Generated by Django 4.2 on 2025-12-04 10:16

from django.db import migrations, models


def add_branch_team_if_missing(apps, schema_editor):
    # Helper to check column existence in MySQL
    def column_exists(table_name, column_name):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            return cursor.fetchone()[0] > 0

    def add_column_if_missing(table_name, column_sql):
        # column_sql must be full fragment like `ADD COLUMN `branch_id` int NULL`
        with schema_editor.connection.cursor() as cursor:
            try:
                cursor.execute(f"ALTER TABLE `{table_name}` {column_sql}")
            except Exception:
                # Ignore if fails (e.g., duplicate) to keep migration idempotent
                pass

    # Tables
    csh_table = 'candidate_status_history'
    cj_table = 'candidate_clientjob'

    # CandidateStatusHistory: branch_id, team_id
    if not column_exists(csh_table, 'branch_id'):
        add_column_if_missing(csh_table, "ADD COLUMN `branch_id` int NULL")
    if not column_exists(csh_table, 'team_id'):
        add_column_if_missing(csh_table, "ADD COLUMN `team_id` int NULL")

    # ClientJob: branch_id, team_id
    if not column_exists(cj_table, 'branch_id'):
        add_column_if_missing(cj_table, "ADD COLUMN `branch_id` int NULL")
    if not column_exists(cj_table, 'team_id'):
        add_column_if_missing(cj_table, "ADD COLUMN `team_id` int NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0050_candidate_feedback_candidate_transfer_history'),
    ]

    operations = [
        migrations.RunPython(add_branch_team_if_missing, reverse_code=migrations.RunPython.noop)
    ]
