# Generated by Cascade to synchronize branch/team columns and migration state
from django.db import migrations, models


def sync_branch_team_fields(apps, schema_editor):
    """Ensure branch_id and team_id exist on both candidate_clientjob and candidate_status_history."""
    def column_exists(table_name, column_name):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            return cursor.fetchone()[0] > 0

    def add_column_if_missing(table_name, column_sql):
        with schema_editor.connection.cursor() as cursor:
            try:
                cursor.execute(f"ALTER TABLE `{table_name}` {column_sql}")
            except Exception:
                # Safe to ignore if duplicate or any non-critical error
                pass

    # Tables
    csh_table = 'candidate_status_history'
    cj_table = 'candidate_clientjob'

    # CandidateStatusHistory
    if not column_exists(csh_table, 'branch_id'):
        add_column_if_missing(csh_table, "ADD COLUMN `branch_id` int NULL")
    if not column_exists(csh_table, 'team_id'):
        add_column_if_missing(csh_table, "ADD COLUMN `team_id` int NULL")

    # ClientJob
    if not column_exists(cj_table, 'branch_id'):
        add_column_if_missing(cj_table, "ADD COLUMN `branch_id` int NULL")
    if not column_exists(cj_table, 'team_id'):
        add_column_if_missing(cj_table, "ADD COLUMN `team_id` int NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0051_candidatestatushistory_branch_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(sync_branch_team_fields, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='clientjob',
                    name='branch_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='clientjob',
                    name='team_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='candidatestatushistory',
                    name='branch_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='candidatestatushistory',
                    name='team_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
        )
    ]
