# Generated by Django 4.2 on 2025-12-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0056_move_feedback_to_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatushistory',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientjob',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
