# Generated by Django 4.2 on 2025-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0057_candidatestatushistory_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatushistory',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientjob',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
