# Generated by Django 4.2.7 on 2025-12-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0058_alter_candidatestatushistory_employee_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['next_follow_up_date'], name='clientjob_nfd_idx'),
        ),
        migrations.AddIndex(
            model_name='clientjob',
            index=models.Index(fields=['expected_joining_date'], name='clientjob_ejd_idx'),
        ),
    ]
