# Generated by Django 4.2 on 2025-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0058_alter_candidatestatushistory_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatushistory',
            name='delete_reason',
            field=models.TextField(blank=True, help_text='Reason for soft delete', null=True),
        ),
        migrations.AddField(
            model_name='candidatestatushistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this row was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='candidatestatushistory',
            name='deleted_by',
            field=models.CharField(blank=True, help_text='Employee code who deleted this row', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidatestatushistory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddIndex(
            model_name='candidatestatushistory',
            index=models.Index(fields=['is_deleted'], name='idx_is_deleted'),
        ),
    ]
