# Generated by Django 4.2.7 on 2025-12-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0059_clientjob_clientjob_nfd_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidatestatushistory',
            index=models.Index(fields=['attend_flag'], name='idx_attend_flag'),
        ),
        migrations.AddIndex(
            model_name='candidatestatushistory',
            index=models.Index(fields=['profile_submission'], name='idx_profile_submission'),
        ),
    ]
