# Generated by Django 4.2.7 on 2025-12-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0060_candidatestatushistory_idx_attend_flag_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['candidate_name'], name='candidate_name_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='candidate_email_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['mobile1'], name='candidate_mobile1_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['mobile2'], name='candidate_mobile2_idx'),
        ),
    ]
