# Generated by Django 4.2.7 on 2025-12-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0061_candidate_candidate_name_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-created_at'], name='candidate_created_at_idx'),
        ),
    ]
