# Generated by Django 5.2.1 on 2025-08-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='designation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
