# Generated by Django 5.2.1 on 2025-09-22 13:56

from django.db import migrations, models


def populate_branch_codes(apps, schema_editor):
    """
    No-op function since the code field already exists in the database.
    This migration was created to add a field that already exists.
    """
    pass


def reverse_populate_branch_codes(apps, schema_editor):
    """
    No-op reverse function
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0014_experience'),
    ]

    operations = [
        # No-op migration since the code field already exists in the database
        migrations.RunPython(
            populate_branch_codes,
            reverse_populate_branch_codes
        ),
    ]
