# Generated by Django 5.2.1 on 2025-09-29 07:27

from django.db import migrations, models


def no_op(apps, schema_editor):
    """
    No-op function since the code field already exists in the database.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0017_branch_code'),
    ]

    operations = [
        # No-op migration since the code field already exists in the database
        migrations.RunPython(no_op, no_op),
    ]
