# Generated by Django 5.2.1 on 2025-09-29 07:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0018_branch_code'),
    ]

    operations = [
        # State-only: declare 'code' on Branch so subsequent rename can occur without DB changes
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='branch',
                    name='code',
                    field=models.CharField(
                        max_length=10,
                        unique=True,
                        help_text='Branch code (e.g., MUM, DEL, BLR)',
                        null=True,
                        blank=True,
                    ),
                ),
            ],
        ),
    ]
