# Generated by Django 5.2.1 on 2025-09-30 09:04

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0019_branch_code'),
    ]

    operations = [
        # State-only: rename 'code' -> 'branchcode' without DB operation
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='branch',
                    old_name='code',
                    new_name='branchcode',
                ),
            ],
        ),
    ]
