# Generated by Django 5.2.1 on 2025-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0021_fix_branch_branchcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branchcode',
            field=models.CharField(default=1, help_text='Branch code (e.g., MUM, DEL, BLR)', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
