# Generated by Django 4.2.7 on 2025-12-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empreg', '0014_remove_employee_payslipfiles_employee_status_and_more'),
        ('Masters', '0022_alter_branch_branchcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='Masters.branch')),
                ('employees', models.ManyToManyField(blank=True, related_name='teams', to='empreg.employee')),
            ],
            options={
                'db_table': 'masters_teams',
            },
        ),
    ]
